/* Committed on purpose: SUPABASE_ANON_KEY is Supabase's public/publishable
 * key (safe to expose client-side — Row Level Security in supabase/schema.sql
 * is what actually protects data, not hiding this value). This is a static
 * app with no server-side build step, so a checked-in file is what makes
 * these values reliably reach every production build/deploy, instead of
 * depending on a local .env that never leaves this machine.
 *
 * FREESOUND_API_KEY is a read-only Freesound "token" key (search + preview
 * playback only, no OAuth2 login involved) — same tradeoff as the Supabase
 * key above: with no backend to hide it behind, it necessarily ships in
 * client-side JS. Worst case if someone extracts and reuses it is Freesound
 * rate-limiting requests against this specific app's Freesound account, not
 * access to anything private. Leave it empty ("") to keep the Sound-Effects
 * search section hidden entirely.
 *
 * Generated by scripts/gen-config.js from .env — re-run `npm run config`
 * after editing .env, then commit the result. Editing this file directly
 * also works fine. */
window.RJ_CONFIG = {
  "SUPABASE_URL": "https://xrghtxlrrdlyxgvjkwko.supabase.co",
  "SUPABASE_ANON_KEY": "sb_publishable_wEwtKrdsxiKmC_hFTQypHg_WntLR_2y",
  "FREESOUND_API_KEY": ""
};
