#!/usr/bin/env node
/*
 * Reads .env (SUPABASE_URL, SUPABASE_ANON_KEY) and writes js/config.js,
 * which index.html loads before js/sync.js. No dependencies on purpose —
 * this is the only "build step" in an otherwise build-free vanilla app.
 * Run via: npm run config
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'js', 'config.js');

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

if (!fs.existsSync(envPath)) {
  console.error('.env nicht gefunden. Kopiere .env.example zu .env und trage deine Supabase-Werte ein.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const url = env.SUPABASE_URL || '';
const anonKey = env.SUPABASE_ANON_KEY || '';

if (!url || url.includes('your-project-ref') || !anonKey || anonKey.includes('your-anon')) {
  console.error('SUPABASE_URL / SUPABASE_ANON_KEY fehlen oder sind noch Platzhalter in .env.');
  process.exit(1);
}

const out = `/* Generated by scripts/gen-config.js from .env — do not edit by hand, do not commit. */\n`
  + `window.RJ_CONFIG = ${JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: anonKey }, null, 2)};\n`;

fs.writeFileSync(outPath, out);
console.log(`js/config.js geschrieben (SUPABASE_URL=${url}).`);
