#!/usr/bin/env node
/*
 * Reads .env (SUPABASE_URL, SUPABASE_ANON_KEY) and writes js/config.js,
 * which index.html loads before js/sync.js. No dependencies on purpose —
 * this is the only "build step" in an otherwise build-free vanilla app.
 * Run via: npm run config
 *
 * js/config.js is committed to the repo (see its own header comment for
 * why) — this script is a convenience for regenerating it locally after
 * editing .env, e.g. when rotating a key. Its output must then be
 * committed like any other source change for a production build to pick
 * it up.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'js', 'config.js');

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

if (!fs.existsSync(envPath)) {
  console.error('.env nicht gefunden. Kopiere .env.example zu .env und trage deine Supabase-Werte ein.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const url = env.SUPABASE_URL || '';
const anonKey = env.SUPABASE_ANON_KEY || '';
// Optional — an empty string just hides the Sound-Effects search section
// (see js/mediasearch.js), so no placeholder-detection/exit(1) needed here
// the way the required Supabase values above get.
const freesoundKey = env.FREESOUND_API_KEY || '';

if (!url || url.includes('your-project-ref') || !anonKey || anonKey.includes('your-anon')) {
  console.error('SUPABASE_URL / SUPABASE_ANON_KEY fehlen oder sind noch Platzhalter in .env.');
  process.exit(1);
}

const out = `/* Committed on purpose: SUPABASE_ANON_KEY is Supabase's public/publishable\n`
  + ` * key (safe to expose client-side — Row Level Security in supabase/schema.sql\n`
  + ` * is what actually protects data, not hiding this value). This is a static\n`
  + ` * app with no server-side build step, so a checked-in file is what makes\n`
  + ` * these values reliably reach every production build/deploy, instead of\n`
  + ` * depending on a local .env that never leaves this machine.\n`
  + ` *\n`
  + ` * FREESOUND_API_KEY is a read-only Freesound "token" key (search + preview\n`
  + ` * playback only, no OAuth2 login involved) — same tradeoff as the Supabase\n`
  + ` * key above. Leave it empty to keep the Sound-Effects search section hidden.\n`
  + ` *\n`
  + ` * Generated by scripts/gen-config.js from .env — re-run \`npm run config\`\n`
  + ` * after editing .env, then commit the result. Editing this file directly\n`
  + ` * also works fine. */\n`
  + `window.RJ_CONFIG = ${JSON.stringify({ SUPABASE_URL: url, SUPABASE_ANON_KEY: anonKey, FREESOUND_API_KEY: freesoundKey }, null, 2)};\n`;

fs.writeFileSync(outPath, out);
console.log(`js/config.js geschrieben (SUPABASE_URL=${url}, FREESOUND_API_KEY=${freesoundKey ? 'gesetzt' : 'leer'}). Bitte committen, damit der nächste Production-Build es enthält.`);
