#!/usr/bin/env node
/*
 * Reads .env (API_BASE_URL, FREESOUND_API_KEY, JAMENDO_CLIENT_ID) and
 * writes js/config.js, which index.html loads before js/sync.js. No
 * dependencies on purpose — this is the only "build step" in an otherwise
 * build-free vanilla app. Run via: npm run config
 *
 * js/config.js is committed to the repo (see its own header comment for
 * why) — this script is a convenience for regenerating it locally, e.g.
 * when rotating FREESOUND_API_KEY/JAMENDO_CLIENT_ID. Its output must then
 * be committed like any other source change for a production build to
 * pick it up.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'js', 'config.js');

function parseEnv(text) {
  const values = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

if (!fs.existsSync(envPath)) {
  console.error('.env nicht gefunden. Kopiere .env.example zu .env und trage deine Werte ein.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const apiBaseUrl = env.API_BASE_URL || '/server/api';
// Optional — an empty string just hides that tab (see js/mediasearch.js),
// so no placeholder-detection/exit(1) needed for these.
const freesoundKey = env.FREESOUND_API_KEY || '';
const jamendoClientId = env.JAMENDO_CLIENT_ID || '';

const out = `/* Committed on purpose - none of these are secrets. API_BASE_URL points at\n`
  + ` * the self-hosted PHP backend (server/api/) that replaced Supabase; the\n`
  + ` * backend itself holds the real, private MySQL credentials in\n`
  + ` * server/config.php, which is gitignored and never reaches the client.\n`
  + ` *\n`
  + ` * FREESOUND_API_KEY is a read-only Freesound "token" key (search + preview\n`
  + ` * playback only, no OAuth2 login involved) — with no backend to hide it\n`
  + ` * behind, it necessarily ships in client-side JS. Leave it empty to keep\n`
  + ` * the Sound-Effects tab hidden.\n`
  + ` *\n`
  + ` * JAMENDO_CLIENT_ID is a public app identifier, not a secret. Leave it\n`
  + ` * empty to keep the Music tab hidden.\n`
  + ` *\n`
  + ` * Generated by scripts/gen-config.js from .env — re-run \`npm run config\`\n`
  + ` * after editing .env, then commit the result. Editing this file directly\n`
  + ` * also works fine. */\n`
  + `window.RJ_CONFIG = ${JSON.stringify({ API_BASE_URL: apiBaseUrl, FREESOUND_API_KEY: freesoundKey, JAMENDO_CLIENT_ID: jamendoClientId }, null, 2)};\n`;

fs.writeFileSync(outPath, out);
console.log(`js/config.js geschrieben (API_BASE_URL=${apiBaseUrl}, FREESOUND_API_KEY=${freesoundKey ? 'gesetzt' : 'leer'}, JAMENDO_CLIENT_ID=${jamendoClientId ? 'gesetzt' : 'leer'}). Bitte committen, damit der nächste Production-Build es enthält.`);
